(()=>{'use strict';
const catalog=window.KVMI_CATALOG,root=document.getElementById('explorer');
if(!root||!catalog)return;
const all=catalog.datasets,$=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let current,category='전체',page=0,column=1;const pageSize=30;
const fmt=x=>typeof x==='number'?x.toLocaleString('ko-KR',{maximumFractionDigits:4}):String(x).replaceAll('_',' ');
const cellText=(x,i)=>current.columnUnits[i]==='년'?String(x):fmt(x);
const meta=(label,value)=>{const n=el('div');n.append(el('dt',label),el('dd',value));return n;};
function filtered(){const q=$('row-search').value.trim().toLocaleLowerCase();return current.rows.filter(r=>r.some(v=>String(v).toLocaleLowerCase().includes(q)));}
function list(){const q=$('dataset-search').value.trim().toLocaleLowerCase();const found=all.filter(d=>(category==='전체'||d.category===category)&&[d.title,d.provider,d.category,d.population,d.id].join(' ').toLocaleLowerCase().includes(q));$('dataset-list').replaceChildren();$('list-count').textContent=`자료 ${found.length}개 / 전체 ${all.length}개`;
for(const d of found){const b=el('button',d.title,'dataset-button');b.type='button';b.setAttribute('aria-current',String(d.id===current?.id));b.append(el('small',d.referenceDate+' · '+d.category));b.addEventListener('click',()=>select(d.id,true));$('dataset-list').append(b);}
if(!found.length)$('dataset-list').append(el('p','검색 결과가 없습니다. 검색어나 주제를 바꿔 주세요.','empty'));}
function setURL(id){const u=new URL(location.href);u.searchParams.set('dataset',id);history.pushState({dataset:id},'',u.pathname+u.search+u.hash);}
function select(id,push=false){const d=all.find(x=>x.id===id);$('id-warning').hidden=!!d||!id;$('id-warning').textContent=d?'':`요청한 자료를 제공 목록에서 찾지 못했습니다. 첫 번째 자료를 표시합니다. 보류 자료는 출처·이용조건에서 확인할 수 있습니다.`;current=d||all[0];page=0;column=current.chartColumns[0]??1;$('row-search').value='';if(push)setURL(current.id);
$('dataset-id').textContent=current.id+' / '+current.category;$('dataset-title').textContent=current.title;
$('dataset-meta').replaceChildren(meta('자료 기준',current.referenceDate),meta('공표·등록',current.publicationDate),meta('단위',current.unit),meta('집계 대상',current.population));$('dataset-note').textContent=current.note;
const sel=$('series');sel.replaceChildren();for(const c of current.chartColumns){const o=el('option',current.columns[c]+' · '+current.columnUnits[c]);o.value=String(c);sel.append(o);}sel.value=String(column);sel.disabled=!current.chartColumns.length;if(!current.chartColumns.length){sel.append(el('option','표로 확인하는 자료'));}
$('source-box').replaceChildren();const source=$('source-box');source.append(el('strong',current.provider));source.append(el('p',current.sourceTitle||current.title));source.append(el('p','이용조건: '+current.rights+' · 확인 '+current.rightsChecked));source.append(el('p','근거 위치: '+current.sourcePage+' / '+current.licenseEvidence));source.append(el('p','KVMI 가공: '+current.transformation));source.append(el('p','자료별 이용조건을 따르며, 원자료 제공기관의 후원·보증·제휴를 뜻하지 않습니다.'));
const links=el('div',undefined,'source-links');for(const [label,url]of[['공식 원문 ↗',current.sourceUrl],['이 자료 이용조건',`/intelligence/statistics-rights.html#${current.id}`],['정적 표 보기',`/intelligence/statistics-research.html#${current.id}`]]){const a=el('a',label);a.href=url;if(url.startsWith('https:'))a.rel='noopener noreferrer';links.append(a);}source.append(links);list();render();}
function makeTable(rows){const table=el('table'),caption=el('caption',current.title+' · '+current.unit);table.append(caption);const head=el('thead'),hr=el('tr');current.columns.forEach((c,i)=>{const th=el('th',c+(i&&typeof current.rows[0]?.[i]==='number'&&current.columnUnits[i]!==current.unit?' ('+current.columnUnits[i]+')':''));th.scope='col';hr.append(th);});head.append(hr);table.append(head);const body=el('tbody');for(const row of rows){const tr=el('tr');row.forEach((v,i)=>{const cell=el(i?'td':'th',cellText(v,i));if(!i)cell.scope='row';tr.append(cell);});body.append(tr);}table.append(body);return table;}
function chart(rows){const bars=$('bars');bars.replaceChildren();if(!current.chartColumns.length){$('chart-status').textContent='단위 또는 지표 의미가 다른 열을 한 축에 섞지 않도록 이 자료는 표로 제공합니다.';return;}if(!rows.length){$('chart-status').textContent='검색 결과가 없어 차트를 표시하지 않습니다.';return;}
const chronological=current.id==='OD-15090948'||current.id==='OD-15123555'||current.columns[0]==='기간';const shown=chronological?rows.slice(-20):rows.slice(0,20);const max=Math.max(...shown.map(r=>Number(r[column])||0),0);const unit=current.columnUnits[column];
$('chart-status').textContent=`${current.columns[column]} · ${unit} · ${chronological?'시간순':'원자료순'} · ${shown.length}/${rows.length}행 표시${rows.length>20?(chronological?' (최근 최대 20시점)':' (앞 20행; 상위 순위 아님)'):''} · ${cellText(shown[0][0],0)} — ${cellText(shown.at(-1)[0],0)} · 막대 축 0–${fmt(max)}`;
for(const row of shown){const r=el('div',undefined,'bar-row'),track=el('div',undefined,'bar-track'),fill=el('div',undefined,'bar-fill');fill.style.width=max?`${Math.max(0,Number(row[column]))/max*100}%`:'0%';track.append(fill);track.setAttribute('aria-hidden','true');r.append(el('span',cellText(row[0],0),'bar-label'),track,el('span',fmt(row[column]),'bar-value'));bars.append(r);}}
function render(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages-1);chart(rows);const slice=rows.slice(page*pageSize,(page+1)*pageSize);$('table-container').replaceChildren(makeTable(slice));$('print-table').replaceChildren(makeTable(rows));$('table-status').textContent=rows.length?`검색 결과 ${rows.length}행 · 표 ${page*pageSize+1}–${page*pageSize+slice.length}행 · CSV·인쇄는 검색 결과 전체`:'검색 결과 0행 · 검색어를 지우면 전체 표를 볼 수 있습니다.';$('page-status').textContent=`${page+1} / ${pages}`;$('prev').disabled=page===0;$('next').disabled=page===pages-1;$('download').disabled=!rows.length;$('download').textContent=`검색 결과 CSV (${rows.length}행)`;}
function safeCell(v){let s=String(v??'');if(typeof v==='string'&&/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
function download(){const rows=filtered();if(!rows.length)return;const headers=['자료ID','자료명','제공기관','자료기준','공표일','모집단','단위','원문URL','이용조건','이용조건URL','가공',...current.columns];const prefix=[current.id,current.title,current.provider,current.referenceDate,current.publicationDate,current.population,current.unit,current.sourceUrl,current.rights,current.licenseUrl,current.transformation];const text='\uFEFF'+[headers,...rows.map(r=>[...prefix,...r])].map(r=>r.map(safeCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download=current.id+'-filtered.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('download-status').textContent=rows.length+'행의 CSV 파일을 생성했습니다. 출처·이용조건 열을 함께 유지해 주세요.';}
$('dataset-search').addEventListener('input',list);$('row-search').addEventListener('input',()=>{page=0;render();});$('series').addEventListener('change',e=>{column=Number(e.target.value);chart(filtered());});$('prev').addEventListener('click',()=>{page--;render();});$('next').addEventListener('click',()=>{page++;render();});$('clear-search').addEventListener('click',()=>{$('row-search').value='';page=0;render();});$('download').addEventListener('click',download);$('print').addEventListener('click',()=>window.print());
for(const name of ['전체',...new Set(all.map(d=>d.category))]){const b=el('button',name);b.type='button';b.setAttribute('aria-pressed',String(name==='전체'));b.addEventListener('click',()=>{category=name;document.querySelectorAll('#category-list button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));list();});$('category-list').append(b);}
addEventListener('popstate',()=>select(new URLSearchParams(location.search).get('dataset')));select(new URLSearchParams(location.search).get('dataset'));$('loading').hidden=true;$('detail-panel').hidden=false;
})();
